apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
<<<<<<< HEAD
  replicas: 2
=======
  replicas: 1
>>>>>>> 18d6e3c83d0fe65379cca5a1cfcfb7502caf8407
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: sanjaysaini2000/react-app:latest
        name: nginx
