apiVersion: v1
kind: Service
metadata:
  name: argo-service
  namespace: default
spec:
  ports:
  - nodePort: 31000
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argo
  type: NodePort
