apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo
  name: argo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo
  template:
    metadata:
      labels:
        app: argo
    spec:
      containers:
      - image: ammad205/argo:1.0
        name: argo
        ports:
        - containerPort: 8090
